services:
  server:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: >
      /bin/bash -c "socat TCP-LISTEN:50051,fork,reuseaddr TCP:spicedb:50051 &
      exec uvicorn main:app --proxy-headers --host 0.0.0.0 --port 80 --workers 2 --reload"
    env_file:
      - ./backend/.env
    environment:
      - REDIS_URL=redis://redis:6379/0
    ports:
      - 8000:80
    volumes:
      - ./backend/src:/app
    networks:
      - database-network

networks:
  database-network:
    driver: bridge
